#!/usr/bin/perl
#
# Project Euler.net
# 
# PROBLEM 2:
#     Each new term in the Fibonacci sequence is generated by adding the previous two 
#     terms. By starting with 1 and 2, the first 10 terms will be:
#
#         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#     By considering the terms in the Fibonacci sequence whose values do not exceed 
#     four million, find the sum of the even-valued terms.
#
# ANSWER: 
#    The sum is: 4613732
#
# @author
# Natalie Kerby :: ndkerby@gmail.com

use strict;

#my $currentNumber = 1;
#my $previousNumber = 1;
#my $sum = 0;
my $max = 4000000;

sub fibonacci
{
    my ($currentNumber, $previousNumber, $sum) = @_;

    my $temp = $currentNumber;
    $currentNumber += $previousNumber;
    $previousNumber = $temp;
    
    if ($currentNumber%2 == 0)
    {
        $sum += $currentNumber;
    }

    if ($currentNumber < $max)
    {
        fibonacci($currentNumber,$previousNumber, $sum);
    }
    
    print "The sum is: " . $sum . "\n";
    exit(0);
}

fibonacci(1,1);